version: '3.8'

services:
  fhirnode_sourcedb_patient:
    image: sourcedbpatient
    container_name: fhirnode_sourcedb_patient
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fhir
    ports:
      - "5431:5432"
    volumes:
      - fhirnode_sourcedb_patient_data:/var/lib/postgresql/data
      - ./init:/init
      - ./init/images:/app/images
    ## run the init scripts for creating the schema and also filling it with fake data - tail command is to keep container running
    command: ["bash", "-c", "docker-entrypoint.sh postgres & sleep 5 && psql -U postgres -f /init/db.sql && python3 /init/synthdata.py -u postgres -p password && tail -f /dev/null"]

  fhirnode_sourcedb_multicorn:
    image: fhirnode_multicorn
    container_name: fhirnode_sourcedb_multicorn
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5430:5432"
      - "5000:5000"
    volumes:
      - fhirnode_sourcedb_multicorn_data:/var/lib/postgresql/data


volumes:
  fhirnode_sourcedb_patient_data:
  fhirnode_sourcedb_multicorn_data:
