version: '3.8'

services:
  fhirnode_sourcedb_multicorn:
    image: fhirnode_multicorn
    container_name: fhirnode_sourcedb_multicorn
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5430:5432"
    volumes:
      - fhirnode_multicorn_data:/var/lib/postgresql/data
  fhirnode_fhirbase:
    image: fhirbase/fhirbase:latest
    container_name: fhirnode_fhirbase_container
    ports:
      - "3000:3000"
      - "5432:5432"
    volumes:
      - fhirnode_fhirbase_data:/pgdata

volumes:
  fhirnode_multicorn_data:
  fhirnode_fhirbase_data:
